(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "FIBO"
   "<FIBO-REQUEST>"
   "FIBO-REQUEST"
   "<FIBO-RESPONSE>"
   "FIBO-RESPONSE"
   "VELOCITY"
   "<VELOCITY-REQUEST>"
   "VELOCITY-REQUEST"
   "<VELOCITY-RESPONSE>"
   "VELOCITY-RESPONSE"
  ))

